title: Rutger Farry
email: rutgerfarry@gmail.com
description: >
  Rutger Farry's blog
url: "https://rutgerfarry.com"
github_username:  rutgerfarry
twitter_username: rutgerfarry
instagram_username: rutgerfarry
resume_url: "https://github.com/rutgerfarry/resume/raw/master/resume.pdf"
google_analytics: UA-59005720-1

# Assign front matter to all images
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
